---------------------------------------------------------
--This will reindex all table major tables and clear all temporary JEV
---------------------------------------------------------
delete BK_T_ARDEBITS_142_TEMP
delete BK_T_APCREDITS_143_TEMP
delete BK_T_TRANSACTION_SUBSIDIARY_133_TEMP
delete BK_T_TRANSACTION_REVIEWED_135_TEMP
delete BK_T_ISPPE_145_TEMP
delete BK_T_ISINTANGIBLE_TEMP
delete BK_T_CIP_147_TEMP
delete BK_T_TRANSACTION_REFERENCE_DETAILS_TEMP
delete BK_T_TRANSACTION_DETAIL_132_TEMP
delete BK_T_TRANSACTION_131_TEMP
delete BK_TMP_PAYABLES_001
delete BK_TMP_PAYABLES_002
delete BK_TMP_PAYABLES_003
delete BK_TMP_PAYABLES_005
delete BK_TMP_PAYABLES_006
delete BK_TMP_PAYABLES_007
delete BK_TMP_PAYABLES_008
delete dbo.BK_TMP_AGING_002
delete dbo.BK_TMP_AGING_003
delete dbo.BK_TMP_AGING_004
delete dbo.BK_TMP_AGING_005
delete dbo.BK_TMP_AGING_006
delete dbo.BK_TMP_AGING_007
delete dbo.BK_TMP_AGING_008
delete dbo.BK_TMP_CASH_FLOW_001
delete dbo.BK_TMP_CASH_FLOW_002
delete dbo.BK_TMP_CASH_FLOW_003


DBCC DBREINDEX ( BK_R_PPE_118 )
go

DBCC DBREINDEX ( BK_T_TRANSACTION_131 )
go

DBCC DBREINDEX ( BK_T_TRANSACTION_DETAIL_132 )
go

DBCC DBREINDEX ( BK_T_TRANSACTION_SUBSIDIARY_133 )
go

DBCC DBREINDEX ( BK_T_ARDEBITS_142 )
go

DBCC DBREINDEX ( BK_T_APCREDITS_143 )
go

DBCC DBREINDEX ( BK_T_ISPPE_145 )
go

DBCC DBREINDEX ( BK_T_ISINTANGIBLE )
go

DBCC DBREINDEX ( BK_H_ANNUAL_BALANCE_171 )
go

DBCC DBREINDEX ( BK_H_Annual_PPEBalance )
go

DBCC DBREINDEX ( BK_R_ACCOUNT_TYPE_101 )
go

DBCC DBREINDEX ( BK_R_AUTHORIZATION )
go

DBCC DBREINDEX ( BK_R_BOOK_103 )
go

DBCC DBREINDEX ( BK_R_CASH_FLOW )
go

DBCC DBREINDEX ( BK_R_CASH_FLOW_ACCOUNTS )
go

DBCC DBREINDEX ( BK_R_CASH_FLOW_TEMPLATES )
go

DBCC DBREINDEX ( BK_R_CashOfficer_200 )
go

DBCC DBREINDEX ( BK_R_DEBTOR_CREDITOR_114 )
go

DBCC DBREINDEX ( BK_R_EMPLOYEE_115 )
go

DBCC DBREINDEX ( BK_R_FINANCING_SOURCE )
go

DBCC DBREINDEX ( BK_R_FUND_104 )
go

DBCC DBREINDEX ( BK_R_FUND_CATEGORY )
go

DBCC DBREINDEX ( BK_R_FUND_CLUSTER )
go

DBCC DBREINDEX ( BK_R_GOVERNMENT_EQUITY )
go

DBCC DBREINDEX ( BK_R_GOVERNMENT_EQUITY_ACCOUNTS )
go

DBCC DBREINDEX ( BK_R_GOVERNMENT_EQUITY_SL )
go

DBCC DBREINDEX ( BK_R_INVENTORY_ITEMS_117 )
go

DBCC DBREINDEX ( BK_R_MAJOR_ACCOUNT_102 )
go

DBCC DBREINDEX ( BK_R_PROJECT_116 )
go

DBCC DBREINDEX ( BK_R_PublicInfra_121 )
go

DBCC DBREINDEX ( BK_R_REFERENCE_DOCUMENT_105 )
go

DBCC DBREINDEX ( BK_R_RESPONSIBILITY_CENTER_107 )
go

DBCC DBREINDEX ( BK_R_RESPONSIBILITY_CENTER_TYPE_106 )
go

DBCC DBREINDEX ( BK_R_SUBSIDIARY_ACCOUNT_113 )
go

DBCC DBREINDEX ( BK_R_SUBSIDIARY_ACCOUNT_RPU )
go

DBCC DBREINDEX ( BK_R_SUBSIDIARY_TYPE_112 )
go

DBCC DBREINDEX ( BK_R_TEMPLATE_BOOK_119 )
go

DBCC DBREINDEX ( BK_R_TEMPLATE_HEADER_109 )
go

DBCC DBREINDEX ( BK_R_TRANSACTION_TYPE_108 )
go

DBCC DBREINDEX ( BK_S_USER_0002 )
go

DBCC DBREINDEX ( BK_SETUP_001 )
go

DBCC DBREINDEX ( BK_TMP_PAYABLES_001 )
go

DBCC DBREINDEX ( BK_TMP_PAYABLES_002 )
go 

DBCC DBREINDEX ( BK_TMP_PAYABLES_003 )
go

DBCC DBREINDEX ( BK_TMP_PAYABLES_005 )
go

DBCC DBREINDEX ( BK_TMP_PAYABLES_006 )
go

DBCC DBREINDEX ( BK_TMP_PAYABLES_007 )
go

DBCC DBREINDEX ( BK_TMP_PAYABLES_008 )
go


Delete BK_T_TRANSACTION_REFERENCE_134
where transaction_no < 0 

Delete BK_T_TRANSACTION_REVIEWED_135
where transaction_no < 0 
  
Delete BK_T_TRANSACTION_REFERENCE_DETAILS  
where transaction_no < 0  
  
Delete BK_T_CIP_147  
where transaction_no < 0  
  
Delete BK_T_TRANSACTION_SUBSIDIARY_133  
where transaction_no < 0  
  
Delete BK_T_ISPPE_145  
where tran_no < 0  
  
Delete BK_T_PublicInfra  
where tran_no < 0  
  
Delete BK_T_APCREDITS_143  
where transaction_no < 0  
  
Delete BK_T_ARDEBITS_142  
where transaction_no < 0    

Delete BK_T_TRANSACTION_DETAIL_132  
where transaction_no < 0  
  
Delete BK_T_Transaction_131  
where transaction_no < 0


GO